### ISSUE TITLE
게임 접속 후 input 입력 작동을 안하는 문제

### ISSUE THREAD

**Issue by redundant4u** [9orani/front#1]
문제:
- 프론트 접속 후 비디오는 정상적으로 스트리밍 되나 입력(키보드, 마우스 등등)이 안되는 문제

예상 원인:
- 프론트 입력 쪽 코드 문제

해결 방법:
- 프론트 테스크 코드 작성하여 빠진 코드가 있다면 추가적으로 코드 push 할 계획

**Comment by redundant4u** [comment]
`InputRemoting` 테스트 코드 작성 중 해당 문제 오류 인지
```
● InputRemoting › startSending

    Please implement this method.

      16 |      */
      17 |     get devices() {
    > 18 |         throw new Error(`Please implement this method.`);
         |               ^
      19 |     }
      20 |
      21 |     /**

      at Sender.get devices [as devices] (src/js/WebRTC/LocalInputManager.js:18:15)
      at InputRemoting.devices [as _sendAllDevices] (src/js/WebRTC/input/InputRemoting.js:66:42)
      at InputRemoting._sendAllDevices [as _sendInitialMessages] (src/js/WebRTC/input/InputRemoting.js:58:14)
      at InputRemoting._sendInitialMessages [as startSending] (src/js/WebRTC/input/InputRemoting.js:38:14)
      at Object.startSending (test/InputRemoting.test.js:26:23)
```

원인:
`InputRemoting`의 `startSending()` `_sendInitialMessages()` `_sendAllDevices()` 순서 로직을 따라 가다 `get devices()`에서 `Sender`의 `get devices()`가 없어서 `LocalInputManager`의 `get devices()`로 빠져서 해당 문제 발생

해결:
`Sender` 클래스에 `get devices()` 부분 추가. [commit 참고](https://github.com/9orani/front/commit/041a646afc2d322c7ddce8a0ee8e0e2f06c87c4c)
